spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: db
    password: 12345

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org.springframework: ERROR
    org.springframework.cloud.netflix.eureka: INFO
    apache.kafka: WARN

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    common-properties:
      bootstrap.servers: localhost:9092
      enable.auto.commit: false
      auto.offset.reset: latest
    consumers:
      - type: SnapshotProcessor
        topics:
          - telemetry.snapshots.v1
        poll-timeout: 500ms
        properties:
          group.id: telemetry.analyzer.snapshot
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorsSnapshotDeserializer
      - type: HubEventProcessor
        topics:
          - telemetry.hubs.v1
        poll-timeout: 2000ms
        properties:
          group.id: telemetry.analyzer.hub
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer